In [2]:
from langchain_openai import ChatOpenAI
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_core.messages import HumanMessage
from langchain_core.messages import SystemMessage
from langgraph.prebuilt import create_react_agent

In [3]:
import mysql.connector
import pandas as pd

# Establish connection to MySQL database
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="mindstix",
    database="edb"
)

# Cursor to fetch tables
cursor = connection.cursor()

# Query to get all table names
cursor.execute("SHOW TABLES")

# Get a list of all table names
tables = [table[0] for table in cursor.fetchall()]

# Create an empty list to store DataFrames
dataframes = []

# Iterate through all tables and load each into a DataFrame
for table in tables:
    query = f"SELECT * FROM {table}"
    df = pd.read_sql(query, con=connection)
    dataframes.append(df)

# Close the connection
connection.close()

# Now you have a list of DataFrames
for i, df in enumerate(dataframes):
    print(f"DataFrame for table {tables[i]}:\n", df.head())  # Print the first few rows of each DataFrame

/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)

DataFrame for table amazon_sale_report:
    index             order_id        date                        status  \
0      0  405-8078784-5731545  2022-04-30                     Cancelled
1      1  171-9198151-1101146  2022-04-30  Shipped - Delivered to Buyer
2      2  404-0687676-7273146  2022-04-30                       Shipped
3      3  403-9615377-8133951  2022-04-30                     Cancelled
4      4  407-1069790-7240320  2022-04-30                       Shipped

  fulfilment sales_channel ship-service-level    style              SKU  \
0   Merchant     Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant     Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon     Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant     Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon     Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        category  ... currency  amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                               None  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True          None
3                                               None  False     Easy Ship
4                                               None  False          None

  unnamed
0    None
1    None
2    None
3    None
4    None

[5 rows x 24 columns]
DataFrame for table cloud_warehouse_compersion:
    shipped_by  inbound  outbound  storage_fee  customer_return
0  Shiprocket        4         7        25.00              6.0
1     INCREFF        4        11         0.15             15.5
DataFrame for table customer_sales:
    index        date  months            customer    style             SKU  \
0      0  2021-06-05  Jun-21  REVATHY LOGANATHAN  MEN5004    MEN5004-KR-L
1      1  2021-06-05  Jun-21  REVATHY LOGANATHAN  MEN5004   MEN5004-KR-XL
2      2  2021-06-05  Jun-21  REVATHY LOGANATHAN  MEN5004  MEN5004-KR-XXL
3      3  2021-06-05  Jun-21  REVATHY LOGANATHAN  MEN5009    MEN5009-KR-L
4      4  2021-06-05  Jun-21  REVATHY LOGANATHAN  MEN5011    MEN5011-KR-L

  size  PCS    rate  gross_amount
0    L    1  616.56         617.0
1   XL    1  616.56         617.0
2  XXL    1  616.56         617.0
3    L    1  616.56         617.0
4    L    1  616.56         617.0
DataFrame for table p_l_march_2021:
    index             SKU    style_id  catalog category  weight   TP_1    TP_2  \
0      0    Os206_3141_S  Os206_3141  Moments    Kurta     0.3  538.0  435.78
1      1    Os206_3141_M  Os206_3141  Moments    Kurta     0.3  538.0  435.78
2      2    Os206_3141_L  Os206_3141  Moments    Kurta     0.3  538.0  435.78
3      3   Os206_3141_XL  Os206_3141  Moments    Kurta     0.3  538.0  435.78
4      4  Os206_3141_2XL  Os206_3141  Moments    Kurta     0.3  538.0  435.78

   MRP_old  final_MRP_old  ajio_MRP  amazon_MRP  amazon_FBA_MRP  flipkart_MRP  \
0   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
1   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
2   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
3   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
4   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0

   limeroad_MRP  myntra_MRP  paytm_MRP  snapdeal_MRP
0        2295.0      2295.0     2295.0        2295.0
1        2295.0      2295.0     2295.0        2295.0
2        2295.0      2295.0     2295.0        2295.0
3        2295.0      2295.0     2295.0        2295.0
4        2295.0      2295.0     2295.0        2295.0
DataFrame for table p_l_may_2022:
    index             SKU    style_id  catalog category  weight     TP  \
0      0    Os206_3141_S  Os206_3141  Moments    Kurta     0.3  538.0
1      1    Os206_3141_M  Os206_3141  Moments    Kurta     0.3  538.0
2      2    Os206_3141_L  Os206_3141  Moments    Kurta     0.3  538.0
3      3   Os206_3141_XL  Os206_3141  Moments    Kurta     0.3  538.0
4      4  Os206_3141_2XL  Os206_3141  Moments    Kurta     0.3  538.0

   MRP_old  final_MRP_old  ajio_MRP  amazon_MRP  amazon_FBA_MRP  flipkart_MRP  \
0   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
1   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
2   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
3   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0
4   2178.0         2295.0    2295.0      2295.0          2295.0        2295.0

   limeroad_MRP  myntra_MRP  paytm_MRP  snapdeal_MRP
0        2295.0      2295.0     2295.0        2295.0
1        2295.0      2295.0     2295.0        2295.0
2        2295.0      2295.0     2295.0        2295.0
3        2295.0      2295.0     2295.0        2295.0
4        2295.0      2295.0     2295.0        2295.0
DataFrame for table stock:
    index       SKU_code design_no  stock       category size color
0      0    AN201-RED-L     AN201      5  AN : LEGGINGS    L   Red
1      1    AN201-RED-M     AN201      5  AN : LEGGINGS    M   Red
2      2    AN201-RED-S     AN201      3  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL     AN201      6  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL     AN201      3  AN : LEGGINGS  XXL   Red

/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)
/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)
/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)
/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)
/var/folders/9r/89zd4rts6k5gy4qdyjc9nsqw0000gn/T/ipykernel_48218/3839740042.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)

In [4]:
dataframes

[         index             order_id        date                        status  \
 0            0  405-8078784-5731545  2022-04-30                     Cancelled
 1            1  171-9198151-1101146  2022-04-30  Shipped - Delivered to Buyer
 2            2  404-0687676-7273146  2022-04-30                       Shipped
 3            3  403-9615377-8133951  2022-04-30                     Cancelled
 4            4  407-1069790-7240320  2022-04-30                       Shipped
 ...        ...                  ...         ...                           ...
 128970  128970  406-6001380-7673107  2022-05-31                       Shipped
 128971  128971  402-9551604-7544318  2022-05-31                       Shipped
 128972  128972  407-9547469-3152358  2022-05-31                       Shipped
 128973  128973  402-6184140-0545956  2022-05-31                       Shipped
 128974  128974  408-7436540-8728312  2022-05-31                       Shipped

        fulfilment sales_channel ship-service-level    style              SKU  \
 0        Merchant     Amazon.in           Standard   SET389   SET389-KR-NP-S
 1        Merchant     Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
 2          Amazon     Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
 3        Merchant     Amazon.in           Standard    J0341       J0341-DR-L
 4          Amazon     Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
 ...           ...           ...                ...      ...              ...
 128970     Amazon     Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
 128971     Amazon     Amazon.in          Expedited   SET401   SET401-KR-NP-M
 128972     Amazon     Amazon.in          Expedited    J0157     J0157-DR-XXL
 128973     Amazon     Amazon.in          Expedited    J0012     J0012-SKD-XS
 128974     Amazon     Amazon.in          Expedited    J0003      J0003-SET-S

              category  ... currency   amount    ship-city    ship-state  \
 0                 Set  ...      INR   647.62       MUMBAI   MAHARASHTRA
 1               kurta  ...      INR   406.00    BENGALURU     KARNATAKA
 2               kurta  ...      INR   329.00  NAVI MUMBAI   MAHARASHTRA
 3       Western Dress  ...      INR   753.33   PUDUCHERRY    PUDUCHERRY
 4                 Top  ...      INR   574.00      CHENNAI    TAMIL NADU
 ...               ...  ...      ...      ...          ...           ...
 128970          kurta  ...      INR   517.00    HYDERABAD     TELANGANA
 128971            Set  ...      INR   999.00     GURUGRAM       HARYANA
 128972  Western Dress  ...      INR   690.00    HYDERABAD     TELANGANA
 128973            Set  ...      INR  1199.00        Halol       Gujarat
 128974            Set  ...      INR   696.00       Raipur  CHHATTISGARH

        ship-postal-code  ship-country  \
 0              400081.0            IN
 1              560085.0            IN
 2              410210.0            IN
 3              605008.0            IN
 4              600073.0            IN
 ...                 ...           ...
 128970         500013.0            IN
 128971         122004.0            IN
 128972         500049.0            IN
 128973         389350.0            IN
 128974         492014.0            IN

                                             promotion-ids    B2B  \
 0                                                    None  False
 1       Amazon PLCC Free-Financing Universal Merchant ...  False
 2            IN Core Free Shipping 2015/04/08 23-48-5-108   True
 3                                                    None  False
 4                                                    None  False
 ...                                                   ...    ...
 128970                                               None  False
 128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False
 128972                                               None  False
 128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False
 128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False

         fulfilled-by unnamed
 0          Easy Ship    None
 1          Easy Ship    None
 2               None    None
 3          Easy Ship    None
 4               None    None
 ...              ...     ...
 128970          None   False
 128971          None   False
 128972          None   False
 128973          None   False
 128974          None   False

 [128975 rows x 24 columns],
    shipped_by  inbound  outbound  storage_fee  customer_return
 0  Shiprocket        4         7        25.00              6.0
 1     INCREFF        4        11         0.15             15.5,
       index        date  months             customer    style             SKU  \
 0         0  2021-06-05  Jun-21   REVATHY LOGANATHAN  MEN5004    MEN5004-KR-L
 1         1  2021-06-05  Jun-21   REVATHY LOGANATHAN  MEN5004   MEN5004-KR-XL
 2         2  2021-06-05  Jun-21   REVATHY LOGANATHAN  MEN5004  MEN5004-KR-XXL
 3         3  2021-06-05  Jun-21   REVATHY LOGANATHAN  MEN5009    MEN5009-KR-L
 4         4  2021-06-05  Jun-21   REVATHY LOGANATHAN  MEN5011    MEN5011-KR-L
 ...     ...         ...     ...                  ...      ...             ...
 2735   2735  2021-08-19  Aug-21  YAMUNAH PUSPANATHAN    J0210      J0210-DR-M
 2736   2736  2021-08-19  Aug-21  YAMUNAH PUSPANATHAN    J0210      J0210-DR-L
 2737   2737  2021-08-19  Aug-21  YAMUNAH PUSPANATHAN    J0210     J0210-DR-XL
 2738   2738  2021-08-19  Aug-21  YAMUNAH PUSPANATHAN    J0210    J0210-DR-XXL
 2739   2739  2021-08-19  Aug-21  YAMUNAH PUSPANATHAN    J0210   J0210-DR-XXXL

       size  PCS    rate  gross_amount
 0        L    1  616.56         617.0
 1       XL    1  616.56         617.0
 2      XXL    1  616.56         617.0
 3        L    1  616.56         617.0
 4        L    1  616.56         617.0
 ...    ...  ...     ...           ...
 2735     M    1  938.00         938.0
 2736     L    1  938.00         938.0
 2737    XL    1  938.00         938.0
 2738   XXL    1  938.00         938.0
 2739  XXXL    1  938.00         938.0

 [2740 rows x 10 columns],
       index             SKU    style_id  catalog category  weight   TP_1  \
 0         0    Os206_3141_S  Os206_3141  Moments    Kurta     0.3  538.0
 1         1    Os206_3141_M  Os206_3141  Moments    Kurta     0.3  538.0
 2         2    Os206_3141_L  Os206_3141  Moments    Kurta     0.3  538.0
 3         3   Os206_3141_XL  Os206_3141  Moments    Kurta     0.3  538.0
 4         4  Os206_3141_2XL  Os206_3141  Moments    Kurta     0.3  538.0
 ...     ...             ...         ...      ...      ...     ...    ...
 1325   1325         Os326_M       Os326      Mix    Kurta     0.3  467.0
 1326   1326         Os326_L       Os326      Mix    Kurta     0.3  467.0
 1327   1327        Os326_XL       Os326      Mix    Kurta     0.3  467.0
 1328   1328       Os326_2XL       Os326      Mix    Kurta     0.3  467.0
 1329   1329       Os326_3XL       Os326      Mix    Kurta     0.3  467.0

         TP_2  MRP_old  final_MRP_old  ajio_MRP  amazon_MRP  amazon_FBA_MRP  \
 0     435.78   2178.0         2295.0    2295.0      2295.0          2295.0
 1     435.78   2178.0         2295.0    2295.0      2295.0          2295.0
 2     435.78   2178.0         2295.0    2295.0      2295.0          2295.0
 3     435.78   2178.0         2295.0    2295.0      2295.0          2295.0
 4     435.78   2178.0         2295.0    2295.0      2295.0          2295.0
 ...      ...      ...            ...       ...         ...             ...
 1325  378.27   1878.0         1995.0    1995.0      1995.0          1995.0
 1326  378.27   1878.0         1995.0    1995.0      1995.0          1995.0
 1327  378.27   1878.0         1995.0    1995.0      1995.0          1995.0
 1328  378.27   1878.0         1995.0    1995.0      1995.0          1995.0
 1329  378.27   1878.0         1995.0    1995.0      1995.0          1995.0

       flipkart_MRP  limeroad_MRP  myntra_MRP  paytm_MRP  snapdeal_MRP
 0           2295.0        2295.0      2295.0     2295.0        2295.0
 1           2295.0        2295.0      2295.0     2295.0        2295.0
 2           2295.0        2295.0      2295.0     2295.0        2295.0
 3           2295.0        2295.0      2295.0     2295.0        2295.0
 4           2295.0        2295.0      2295.0     2295.0        2295.0
 ...            ...           ...         ...        ...           ...
 1325        1995.0        1995.0      1995.0     1995.0        1995.0
 1326        1995.0        1995.0      1995.0     1995.0        1995.0
 1327        1995.0        1995.0      1995.0     1995.0        1995.0
 1328        1995.0        1995.0      1995.0     1995.0        1995.0
 1329        1995.0        1995.0      1995.0     1995.0        1995.0

 [1330 rows x 18 columns],
       index             SKU    style_id  catalog category  weight     TP  \
 0         0    Os206_3141_S  Os206_3141  Moments    Kurta     0.3  538.0
 1         1    Os206_3141_M  Os206_3141  Moments    Kurta     0.3  538.0
 2         2    Os206_3141_L  Os206_3141  Moments    Kurta     0.3  538.0
 3         3   Os206_3141_XL  Os206_3141  Moments    Kurta     0.3  538.0
 4         4  Os206_3141_2XL  Os206_3141  Moments    Kurta     0.3  538.0
 ...     ...             ...         ...      ...      ...     ...    ...
 1325   1325         Os326_M       Os326      Mix    Kurta     0.3  467.0
 1326   1326         Os326_L       Os326      Mix    Kurta     0.3  467.0
 1327   1327        Os326_XL       Os326      Mix    Kurta     0.3  467.0
 1328   1328       Os326_2XL       Os326      Mix    Kurta     0.3  467.0
 1329   1329       Os326_3XL       Os326      Mix    Kurta     0.3  467.0

       MRP_old  final_MRP_old  ajio_MRP  amazon_MRP  amazon_FBA_MRP  \
 0      2178.0         2295.0    2295.0      2295.0          2295.0
 1      2178.0         2295.0    2295.0      2295.0          2295.0
 2      2178.0         2295.0    2295.0      2295.0          2295.0
 3      2178.0         2295.0    2295.0      2295.0          2295.0
 4      2178.0         2295.0    2295.0      2295.0          2295.0
 ...       ...            ...       ...         ...             ...
 1325   1878.0         1995.0    1995.0      1995.0          1995.0
 1326   1878.0         1995.0    1995.0      1995.0          1995.0
 1327   1878.0         1995.0    1995.0      1995.0          1995.0
 1328   1878.0         1995.0    1995.0      1995.0          1995.0
 1329   1878.0         1995.0    1995.0      1995.0          1995.0

       flipkart_MRP  limeroad_MRP  myntra_MRP  paytm_MRP  snapdeal_MRP
 0           2295.0        2295.0      2295.0     2295.0        2295.0
 1           2295.0        2295.0      2295.0     2295.0        2295.0
 2           2295.0        2295.0      2295.0     2295.0        2295.0
 3           2295.0        2295.0      2295.0     2295.0        2295.0
 4           2295.0        2295.0      2295.0     2295.0        2295.0
 ...            ...           ...         ...        ...           ...
 1325        1995.0        1995.0      1995.0     1995.0        1995.0
 1326        1995.0        1995.0      1995.0     1995.0        1995.0
 1327        1995.0        1995.0      1995.0     1995.0        1995.0
 1328        1995.0        1995.0      1995.0     1995.0        1995.0
 1329        1995.0        1995.0      1995.0     1995.0        1995.0

 [1330 rows x 17 columns],
       index           SKU_code design_no  stock       category  size color
 0         0        AN201-RED-L     AN201      5  AN : LEGGINGS     L   Red
 1         1        AN201-RED-M     AN201      5  AN : LEGGINGS     M   Red
 2         2        AN201-RED-S     AN201      3  AN : LEGGINGS     S   Red
 3         3       AN201-RED-XL     AN201      6  AN : LEGGINGS    XL   Red
 4         4      AN201-RED-XXL     AN201      3  AN : LEGGINGS   XXL   Red
 ...     ...                ...       ...    ...            ...   ...   ...
 9230   9230     SET462-KR-NP-S    SET462     44            SET     S  Teal
 9231   9231    SET462-KR-NP-XL    SET462     58            SET    XL  Teal
 9232   9232    SET462-KR-NP-XS    SET462     20            SET    XS  Teal
 9233   9233   SET462-KR-NP-XXL    SET462     66            SET   XXL  Teal
 9234   9234  SET462-KR-NP-XXXL    SET462     40            SET  XXXL  Teal

 [9235 rows x 7 columns]]

In [5]:
from langchain_experimental.agents import create_pandas_dataframe_agent


llm = ChatOpenAI(model="gpt-4o-mini")

# agent = create_pandas_dataframe_agent(llm, dataframes, agent_type="openai-tools", verbose=True, allow_dangerous_code=True)

In [6]:
import os
import pandas as pd
from pandasai import Agent, PandasAI
from pandasai.llm.openai import OpenAI
from dotenv import load_dotenv

load_dotenv()


openai_api_key = os.getenv("OPENAI_API_KEY")

# def chat_with_csv(df,prompt):
#     llm = OpenAI(api_token=openai_api_key)
#     pandas_ai = PandasAI(llm)
#     result = pandas_ai.run(df, prompt=prompt)
#     print(result)
#     return result

agent = Agent(dataframes)
agent.chat('Which are the top 5 countries by sales?')

LLMNotFoundError: LLM is required

In [13]:
chat_with_csv(dataframes, 'give nuber of order with amount less than 1000')

/Users/apple/Documents/hackathon_ai/ai-commerce-insights/.venv/lib/python3.9/site-packages/pandasai/__init__.py:147: UserWarning: `PandasAI` (class) is deprecated since v1.0 and will be removed in a future release. Please use `SmartDataframe` instead.
  warnings.warn(

107847

107847